---
namespace: insolar
bases:
  - https://github.com/insolar/gitops/mainnet/overlays/autotests?ref=REL-59
images:
  - name: insolar/mainnet-observer
    newName: localhost/mainnet-observer
    newTag: local
generatorOptions:
  disableNameSuffixHash: true
